name: SecurityAdditions
version: 'b1'
main: com.guedosha.securityadditions.Securityadditions
api-version: 1.19
authors: [ Guedosha ]
description: Prevents non opped players from performing certain actions as a security mesure.
website: guedosha.com
